opt_in_rules:
  - attributes
  - closure_spacing
  - explicit_self
  - vertical_whitespace_between_cases
  - yoda_condition

included:
  - FocusTimer/FocusTimer
excluded:
  - FocusTimer/FocusTimerTests
  - FocusTimer/FocusTimerUITests

line_length: 140

identifier_name:
  min_length: 2
  excluded: [id, URL, x, y]
